---
title: Project Review Template 
author: Marco Reina
date: 05/01/2026
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
---

# Overview

Title of project: Modeling for _Salmonella_ complexity in a suburban creek

Name of project author(s): Esther Palmer

Name of project reviewer: Marco Reina


# Instructions

Write your comments and feedback below for each section/component of the project. The goal should be to help the author improve their project. Make comments as constructive and actionable as possible. You can provide both criticism and praise.

For each component, pick one summary statement by deleting the ones that do not apply and keeping only the one that you think most closely summarizes a given component. 

Make sure your final document compiles/renders into a readable, well-formatted html document.

Delete any sections/text of this template that are not part of your final review document. (Including these instructions.)


# Specific project content evaluation
Evaluate the different parts of the project by filling in the sections below.


## Background, Context and Motivation
How well is the context of the project described? Is a comprehensive background, including summary of previous/related work given? Is the project well placed into the context of existing work (including proper referencing of existing work). Is it clear why the project was undertaken and what new information it hopes to provide?

### Feedback and Comments

* Marco Reina
- Some citations are missing
- I probably would remove the "stupid politics" 
- I would remove any of the instructions within the manuscript
- For the Background I would introduce CRISPR-SeroSeq and why it is such a innovative tool (can determine all the serovars within a sample), i think this is important. Because part of the nuance that no other paper have done it is because there was no good tool for it before (Not even SeqSero2 is as good)

### Summary assessment (PICK ONE, DELETE THE OTHERS)

* some contextualization and motivation

## Question description
How well and clear are the question(s)/hypotheses the project aims to address described? Is it clear how the questions relate to the data?

### Feedback and Comments

* Marco Reina
- Section 3.4, reads as a question, and this is not required if you split your data or use folds for the cv

### Summary assessment

* question/hypotheses unclear

## Data description
How well is the data overall described? Is the source provided? Is a codebook or other meta-information available that makes it clear what the data is? 

### Feedback and Comments

* Marco Reina:
- For the Description of data and data source I would list with bullet points the variables that were selected
- Please provide % of Salmonella prevalence before discarding route of analysis
- Section 2.3 reads more like background rather than a specific question or hypothesis to address
- Please remove all code chunks
- I would provide a table for important variables presented from enviro_rawdata

### Summary assessment

* source and overall structure of data somewhat explained

## Data wrangling and exploratory analysis
How well is the data cleaned/processed and explored? Are all steps reasonable and well explained? Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?

### Feedback and Comments

* Marco Reina
Need more to be more descriptive

### Summary assessment

* some weaknesses in wrangling and exploratory component



## Appropriateness of Analysis
Were the analysis methods appropriate for the data? Was the analysis done properly? Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?

### Feedback and Comments

* Marco Reina:
Results are not in the manuscript, can't be directly assessed. I saw some Linear models in the statistical-analysis.R but I did not understand the context.

### Summary assessment

* defensible but not optimal analysis 


## Presentation
How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality? 

### Feedback and Comments

* Marco Reina:
Results are not in the manuscript, can't be directly assessed.
Figures obtained by running the code need polishing to be publication ready.

### Summary assessment

* results are poorly presented, hard to understand, poor quality



## Discussion/Conclusions
Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?

### Feedback and Comments

* Marco Reina: 
Discussion/Conclusions are not in the manuscript, can't be assessed.

### Summary assessment
* major parts of discussion missing or wrong 


## Further comments

I see work done in the R files that contain the eda, data processing, and statiscal analysis but that work is not reflected in the manuscript.



# Overall project content evaluation
Evaluate overall features of the project  by filling in the sections below.


## Structure
Is the project well structured? Are files in well labeled folders? Do files have reasonable names? Are all "junk" files not needed for analysis/reproduction removed? By just looking at files and folders, can you get an idea of how things fit together?

### Feedback and Comments

* Marco Reina: 
Please delete files and figures that are not part of the project


### Summary assessment

* mostly clear, but some confusing parts (e.g. useless files, things in the wrong folders)


## Documentation 
How well is the project documented? Are you able to understand each step of the whole analysis, each decision that was made, and each line of code? Is enough information provided as comments in code or as part of Rmd files? 

### Feedback and Comments

* Marco Reina: 
Please provide instructions on how to run the code

### Summary assessment
* poorly documented




## Reproducibility
Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention? Are you able to re-run the whole analysis without having to do manual interventions/edits?

### Feedback and Comments

* Marco Reina: 
Some objects were not defined in the code
Once they were silenced, the code ran without issues. Here are the errors observed:
Error:
! object 'df5' not found
Hide Traceback
    ▆
 1. └─base::source(...)
 2.   ├─base::withVisible(eval(ei, envir))
 3.   └─base::eval(ei, envir)
 4.     └─base::eval(ei, envir)

Error:
! object 'rf_train_pred' not found
Hide Traceback
    ▆
 1. ├─base::source(...)
 2. │ ├─base::withVisible(eval(ei, envir))
 3. │ └─base::eval(ei, envir)
 4. │   └─base::eval(ei, envir)
 5. ├─rf_train_pred %>% ... at code/analysis-code/statistical-analysis.R:295:1
 6. └─yardstick::rmse(., truth = complexity, estimate = .pred)

Error:
! object 'rf_fit' not found
Hide Traceback
    ▆
 1. ├─base::source(...)
 2. │ ├─base::withVisible(eval(ei, envir))
 3. │ └─base::eval(ei, envir)
 4. │   └─base::eval(ei, envir)
 5. ├─rf_fit %>% extract_fit_parsnip() %>% vip::vip() at code/analysis-code/statistical-analysis.R:298:1
 6. ├─vip::vip(.)
 7. └─hardhat::extract_fit_parsnip(.)

Warning messages:
1: Removed 18 rows containing missing values or values outside the scale range (`geom_point()`). 
2: Removed 18 rows containing missing values or values outside the scale range (`geom_point()`). 
3: Removed 18 rows containing missing values or values outside the scale range (`geom_point()`). 
4: Removed 17 rows containing missing values or values outside the scale range (`geom_point()`). 
5: Removed 16 rows containing missing values or values outside the scale range (`geom_point()`). 
6: Removed 16 rows containing missing values or values outside the scale range (`geom_point()`). 
7: Removed 16 rows containing missing values or values outside the scale range (`geom_point()`). 
8: Removed 15 rows containing missing values or values outside the scale range (`geom_point()`). 


### Summary assessment

* small parts not reproducible or required manual intervention 



## Thoroughness
How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?

### Feedback and Comments

* Marco Reina: 
Project is not completed, can't be assessed.

### Summary assessment
* weak level of thoroughness


## Further comments

Manuscript needs the most work, results section and discussion needs to be included.





